name: Build Windows GUI App with Icon

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MinGW
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Compile resource file
        run: |
          x86_64-w64-mingw32-windres src/app.rc -O coff -o app_res.o

      - name: Build GUI .exe with icon
        run: |
          x86_64-w64-mingw32-gcc -Wall -O2 -mwindows src/main.c app_res.o -o CreateDateFolder.exe

      - name: Upload release artifact
        uses: softprops/action-gh-release@v2
        with:
          files: CreateDateFolder.exe
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
